# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.2'
    - run: flutter pub get
    # Build apk.
    - run: flutter build apk --split-per-abi --no-sound-null-safety
    # This action will create a github release and optionally upload an artifact to it.
    # https://github.com/ncipollo/release-action
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
          artifacts: "build/app/outputs/apk/debug/*.apk,build/macos/Build/Products/Release/*.app"
          token: ${{ secrets.GITHUB_TOKEN }}
