# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.2'
    - run: flutter pub get
    - run: flutter build apk --debug
    - uses: ncipollo/release-action@v1
      with:
       artifacts: "build/app/outputs/apk/debug/*.apk"
       token: $
